[package]
name = "virtio-drivers"
version = "0.1.0"
authors = ["sen <yjghdsss@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile = "0.2"
log = "0.4"
bitflags = "1.2"